/**
 * Secrets and plain variables available on the Worker's `env`.
 *
 * `worker-configuration.d.ts` is regenerated by `wrangler types` and only ever
 * contains bindings declared in `wrangler.jsonc` — D1, R2, assets. Secrets set
 * with `wrangler secret put` never appear there, so they are declared here and
 * merged into the same global `Env` interface.
 *
 * Every entry is optional on purpose. A secret that has not been set is simply
 * absent at runtime, and the code that reads it must handle that rather than
 * assume the deploy was configured correctly.
 *
 * Keep this list in sync with `.env.example` and with the `wrangler secret put`
 * commands in docs/ARCHITECTURE.md.
 *
 * These go on `Cloudflare.Env`, not the global `Env`: the `env` object exported
 * by `cloudflare:workers` is typed as `Cloudflare.Env`, and the two are separate
 * declarations even though Wrangler generates both from the same bindings.
 */
interface SiteSecrets {
	/** Turnstile secret key. Without it, form submission fails closed. */
	TURNSTILE_SECRET?: string

	/** Resend API key, plus the addresses notifications are sent between. */
	RESEND_API_KEY?: string
	NOTIFY_EMAIL_FROM?: string
	NOTIFY_EMAIL_TO?: string

	/** Telegram bot credentials for team notifications. */
	TELEGRAM_BOT_TOKEN?: string
	TELEGRAM_CHAT_ID?: string

	/** Optional automation webhook. */
	N8N_WEBHOOK_URL?: string
}

declare namespace Cloudflare {
	interface Env extends SiteSecrets {}
}

interface Env extends SiteSecrets {}
