import { execFileSync } from 'node:child_process'
import { mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * The no-AI-attribution rule (CLAUDE.md §0) is enforced by a script that runs in
 * both the pre-commit hook and CI. These tests keep that script honest.
 */

const SCRIPT = 'scripts/check-no-attribution.mjs'

function runGuard(contents: string, filename = 'sample.ts') {
	const dir = mkdtempSync(join(tmpdir(), 'attr-guard-'))
	const file = join(dir, filename)
	writeFileSync(file, contents, 'utf8')
	try {
		execFileSync('node', [SCRIPT, file], { encoding: 'utf8', stdio: 'pipe' })
		return { ok: true, output: '' }
	} catch (error) {
		const err = error as { stderr?: string }
		return { ok: false, output: err.stderr ?? '' }
	}
}

describe('no-AI-attribution guard', () => {
	it('passes ordinary source', () => {
		expect(runGuard('export const answer = 42\n').ok).toBe(true)
	})

	it.each([
		['co-author trailer', 'Co-Authored-By: Claude <noreply@anthropic.com>'],
		['generation note', '// Generated with Claude Code'],
		['authorship claim', '/* This module was written by an AI */'],
		['robot marker', '🤖 Generated with something'],
	])('rejects %s', (_label, line) => {
		const result = runGuard(`const x = 1\n${line}\n`)
		expect(result.ok).toBe(false)
		expect(result.output).toContain('non-negotiable')
	})

	it('does not flag ordinary uses of the word "generated"', () => {
		expect(runGuard('// Types generated by wrangler; do not edit.\n').ok).toBe(true)
	})
})
